export const FETCH_PRODUCTS_SUCCESS= 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS'
export const SHOW_PROD = 'SHOW_PROD'
export const GET_BY_PRODUCT_CAT = 'GET_BY_PRODUCT_CAT'
export const SET_PRICE = 'SET_PRICE'

export const ADD_TO_CART = 'ADD_TO_CART'
export const FETCH_CART = 'FETCH_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'





